const $=id=>document.getElementById(id);
const video=$('preview'),statusText=$('statusText'),effectName=$('effectName');
const intensity=$('intensity'),intensityValue=$('intensityValue'),zoom=$('zoom'),zoomValue=$('zoomValue');
const recordBtn=$('record'),downloadBtn=$('download'),muteBtn=$('mute'),switchBtn=$('switchCam');
const cameraNote=$('cameraNote'),micLevel=$('micLevel'),audioState=$('audioState'),recordTimer=$('recordTimer');
let facing='user',stream=null,audioCtx=null,source=null,destination=null,recorder=null,chunks=[];
let current='normal',muted=false,recordedUrl=null,inputAnalyser=null,raf=0,timerId=0,startedAt=0;
let nodes=null,hardwareZoom=false,zoomValueNum=1,recordingAudioMode='';
const effects={normal:{low:20,high:20000,dist:0,dry:1},robot:{low:180,high:5000,dist:10,dry:.62},demon:{low:65,high:4800,dist:7,dry:.66},radio:{low:320,high:3300,dist:12,dry:.58},glitch:{low:140,high:7000,dist:18,dry:.52}};
function curve(amount){const n=44100,c=new Float32Array(n),k=Math.max(0,amount)/100*8;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(1+k)*x/(1+k*Math.abs(x));}return c}
function applyEffect(){if(!nodes)return;const e=effects[current],p=Number(intensity.value)/100;nodes.low.frequency.value=e.low;nodes.high.frequency.value=e.high;nodes.dist.curve=curve(e.dist*p);nodes.dist.oversample='4x';nodes.dry.gain.value=muted?0:(current==='normal'?1:(e.dry+(1-e.dry)*(1-p)));nodes.wet.gain.value=muted?0:(current==='normal'?0:Math.min(.45,.08+.34*p));nodes.input.gain.value=1;effectName.textContent=current.toUpperCase()}
function rms(an){if(!an)return 0;const d=new Uint8Array(an.fftSize);an.getByteTimeDomainData(d);let s=0;for(const v of d){const x=(v-128)/128;s+=x*x}return Math.sqrt(s/d.length)}
function monitorMic(){cancelAnimationFrame(raf);const tick=()=>{const r=rms(inputAnalyser),p=Math.min(100,Math.round(r*700));micLevel.style.width=p+'%';audioState.textContent=r>.005?'MIC OK':'ESPERANDO MIC';audioState.style.color=r>.005?'#55ff9a':'#ffb347';raf=requestAnimationFrame(tick)};tick()}
function formatTime(ms){let s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function startTimer(){startedAt=performance.now();recordTimer.classList.add('live');cancelAnimationFrame(timerId);const tick=()=>{recordTimer.textContent=formatTime(performance.now()-startedAt);if(recorder?.state==='recording')timerId=requestAnimationFrame(tick)};tick()}
function stopTimer(){cancelAnimationFrame(timerId);recordTimer.classList.remove('live');recordTimer.textContent='00:00'}
function setStatus(t){statusText.textContent=t}
async function setupAudio(s){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Web Audio no disponible');if(audioCtx){try{await audioCtx.close()}catch{}}audioCtx=new AC({latencyHint:'interactive'});source=audioCtx.createMediaStreamSource(s);destination=audioCtx.createMediaStreamDestination();const input=audioCtx.createGain(),low=audioCtx.createBiquadFilter(),high=audioCtx.createBiquadFilter(),dist=audioCtx.createWaveShaper(),dry=audioCtx.createGain(),wet=audioCtx.createGain();low.type='lowpass';high.type='highpass';inputAnalyser=audioCtx.createAnalyser();inputAnalyser.fftSize=1024;source.connect(inputAnalyser);source.connect(input);input.connect(low);low.connect(high);high.connect(dist);dist.connect(wet);wet.connect(destination);source.connect(dry);dry.connect(destination);nodes={input,low,high,dist,dry,wet};await audioCtx.resume();const track=destination.stream.getAudioTracks()[0];if(track)track.enabled=true;applyEffect();monitorMic()}
async function startCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:{ideal:1920},height:{ideal:1080}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});video.srcObject=stream;await video.play();zoomValueNum=1;zoom.value=1;video.style.transform='scale(1)';await setupAudio(stream);await applyZoom();setStatus('CÁMARA LISTA')}
async function applyZoom(){const track=stream?.getVideoTracks()[0];if(!track)return;const caps=track.getCapabilities?.()||{};hardwareZoom=typeof caps.zoom==='object';if(hardwareZoom){zoom.min=caps.zoom.min??1;zoom.max=Math.min(caps.zoom.max??4,4);try{await track.applyConstraints({advanced:[{zoom:zoomValueNum}]});video.style.transform='scale(1)'}catch{hardwareZoom=false}}if(!hardwareZoom)video.style.transform=`scale(${Math.max(1,zoomValueNum)})`;cameraNote.textContent=(hardwareZoom?'ZOOM CÁMARA':'ZOOM DIGITAL')+' · '+zoomValueNum.toFixed(1)+'×'}
document.querySelectorAll('.effect').forEach(b=>b.onclick=()=>{document.querySelectorAll('.effect').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.effect;applyEffect()});
intensity.oninput=()=>{intensityValue.textContent=intensity.value+'%';applyEffect()};zoom.oninput=async()=>{zoomValueNum=Number(zoom.value);await applyZoom()};muteBtn.onclick=()=>{muted=!muted;muteBtn.textContent=muted?'🔇':'🎙️';applyEffect()};switchBtn.onclick=async()=>{facing=facing==='user'?'environment':'user';try{await startCamera()}catch(e){console.error(e);setStatus('NO SE PUDO CAMBIAR')}};
recordBtn.onclick=async()=>{if(recorder?.state==='recording'){recorder.stop();return}try{if(!audioCtx)await setupAudio(stream);if(audioCtx.state!=='running')await audioCtx.resume();const vt=stream?.getVideoTracks()[0],at=destination?.stream.getAudioTracks()[0];if(!vt||!at)throw Error('No hay pistas de video/audio');at.enabled=!muted;chunks=[];const combined=new MediaStream([vt,at]);const types=['video/webm;codecs=vp8,opus','video/webm;codecs=vp9,opus','video/webm'];const mime=types.find(t=>MediaRecorder.isTypeSupported(t))||'';recorder=new MediaRecorder(combined,mime?{mimeType:mime,audioBitsPerSecond:128000,videoBitsPerSecond:5000000}:undefined);recordingAudioMode=current==='normal'?'MICRÓFONO':'VOZ '+current.toUpperCase();recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onerror=e=>{console.error(e);recordBtn.classList.remove('recording');stopTimer();setStatus('ERROR DE GRABACIÓN')};recorder.onstop=()=>{recordBtn.classList.remove('recording');stopTimer();const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});if(recordedUrl)URL.revokeObjectURL(recordedUrl);recordedUrl=URL.createObjectURL(blob);downloadBtn.disabled=false;downloadBtn.onclick=()=>{const a=document.createElement('a');a.href=recordedUrl;a.download='neo-cam-'+Date.now()+'.webm';a.click()};setStatus('VIDEO LISTO · '+recordingAudioMode)};recorder.start(250);recordBtn.classList.add('recording');setStatus('GRABANDO · '+recordingAudioMode);startTimer()}catch(e){console.error(e);recordBtn.classList.remove('recording');stopTimer();setStatus('NO SE PUDO GRABAR')}};
recordTimer.textContent='00:00';
(async()=>{try{await startCamera()}catch(e){console.error(e);setStatus('PERMISO DE CÁMARA REQUERIDO')}})();
